#!/usr/bin/env python3
import csv
import datetime
from pathlib import Path
import speedtest

servers = []
threads = None

s = speedtest.Speedtest()
s.get_servers(servers)
s.get_best_server()
s.download(threads=threads)
s.upload(threads=threads)
s.results.share()

results_dict = s.results.dict()

relcwd = Path(__file__).parent
filepath = Path(relcwd, "data.csv") 
row = [results_dict["timestamp"], 
       results_dict["download"],
       results_dict["upload"],
       results_dict["ping"]]
print(filepath, row)
with open(filepath, "a") as f:
    writer = csv.writer(f)
    writer.writerow(row)

